# Generated by Django 4.1.7 on 2023-05-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasurehunt',
            name='level',
            field=models.IntegerField(choices=[(1, 'level1'), (2, 'level2'), (3, 'level3'), (4, 'level4')]),
        ),
    ]
