# Generated by Django 4.1.7 on 2023-05-07 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0005_useranswer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAnswer',
        ),
    ]
