# Generated by Django 4.1.7 on 2023-05-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0006_delete_useranswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasurehunt',
            name='score',
            field=models.IntegerField(default=5),
        ),
    ]
