# Generated by Django 4.1.7 on 2023-05-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0007_treasurehunt_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasurehunt',
            name='totscore',
            field=models.IntegerField(default=5),
        ),
    ]
